name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.139.0'

    - name: print
      run: pwd

    - name: ls
      run: ls -a

    - name: Build Hugo site
      run: hugo --config hugo.toml

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: aws s3 sync ./public/. ${{ secrets.S3_HOST_BUCKET }}
    
